apiVersion: v1
kind: Service
metadata:
  name: {{ include "gothic2-online.fullname" . }}
  labels:
    {{- include "gothic2-online.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: gametcp
      protocol: TCP
      name: gametcp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.port }}
      targetPort: gameudp
      protocol: UDP
      name: gameudp
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "gothic2-online.selectorLabels" . | nindent 4 }}
