name: Main

on:
  push:
    branches:
      - 'add-ci'

jobs:
  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        env:
          IMAGE_PUSH: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${GITHUB_REPOSITORY_OWNER} --password-stdin
          ./hack/build-images.sh
